[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-v --cov=src --cov-report=term --cov-report=xml --cov-fail-under=85"
testpaths = [
    "tests"
]

[tool.coverage.run]
source = ["src"]
branch = true

[tool.coverage.report]
show_missing = true
fail_under = 85